### ISSUE TITLE
May I link to this from my repo.

### ISSUE THREAD

**Issue by mon5termatt** [SphaeroX/Sovol-SV08-Tweaks#1]
https://github.com/mon5termatt/SV08-Community

I'm trying to compile mods for this printer. Would it be ok to link to these files on my repo.

**Comment by SphaeroX** [comment]
Sorry, I only will post my own modifications here for better overview

**Comment by mon5termatt** [comment]
That's fine. I was just asking if I could add a link to this repo for people who want more mods.
